// E00-T05 · clean-clone reproducibility (EARS-E00-12, EARS-E00-14).
//
// The risk this addresses: E00 works on the machine that built it. A fresh
// clone that needs an undocumented step, a globally installed SDK, or a
// leftover generated file is not a reproducible foundation — and the person who
// discovers that is the next contributor, on their first day.
//
// This does NOT re-run `make verify` inside itself; that would take many minutes
// and duplicate what `verify-clean-clone.sh` already does. It asserts the
// properties that make a clean clone possible, and that the gate itself is
// wired everywhere it must be.

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

function read(path: string): string {
  return readFileSync(join(repositoryRoot, path), 'utf8');
}

function git(...args: string[]): string {
  return execFileSync('git', args, {
    cwd: repositoryRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

test('test_EARS_E00_12_clean_clone_verify_is_green', () => {
  // The gate exists, is executable, and covers every stage. Asserted by name so
  // a step cannot be quietly dropped to make the build go green.
  const script = 'scripts/verify-clean-clone.sh';
  assert.ok(existsSync(join(repositoryRoot, script)), 'the clean-clone gate is missing');

  const source = read(script);
  for (const stage of [
    'check-toolchain.sh',
    'pnpm install --frozen-lockfile',
    'flutter pub get',
    'check:tokens',
    'check:api',
    'pnpm lint',
    'flutter analyze',
    'pnpm format',
    'run build',
    'scan-secrets.sh',
    'pnpm test',
    'flutter test',
    'verify-compose.sh',
    'tests/e2e',
  ]) {
    assert.ok(source.includes(stage), `the clean-clone gate does not run ${stage}`);
  }

  // Every step must run even after one fails. Stopping at the first turns a
  // full picture into repeated multi-minute rounds of whack-a-mole.
  assert.match(source, /FAILED\+=/);
  assert.ok(!source.includes('set -euo pipefail'), 'the gate aborts at the first failure');
});

test('test_EARS_E00_12_pinned_toolchain_is_declared_in_one_place_each', () => {
  // A version pinned in two places drifts. Each tool has exactly one source of
  // truth, and the CI workflow must agree with it.
  const nodeVersion = read('.node-version').trim();
  const flutterVersion = read('.flutter-version').trim();
  const packageJson = JSON.parse(read('package.json')) as {
    packageManager: string;
    engines: { node: string };
  };

  assert.equal(packageJson.engines.node, nodeVersion);
  assert.match(packageJson.packageManager, /^pnpm@\d+\.\d+\.\d+$/);

  const ci = read('.github/workflows/ci.yml');
  assert.ok(ci.includes(nodeVersion), `CI does not pin Node ${nodeVersion}`);
  assert.ok(ci.includes(flutterVersion), `CI does not pin Flutter ${flutterVersion}`);
});

test('test_EARS_E00_12_no_generated_artifact_is_required_before_install', () => {
  // Generated output must be reproducible, not a prerequisite a fresh clone
  // lacks. Anything generated is either committed or regenerated by a
  // documented command — never assumed present.
  const gitignore = read('.gitignore');

  for (const generated of [
    'apps/mobile/lib/l10n/generated/',
    '.dart_tool/',
    'apps/mobile/build/',
  ]) {
    assert.ok(gitignore.includes(generated), `${generated} is not ignored`);
  }

  // The API clients ARE committed, so drift is detectable in review.
  const trackedTs = git('ls-files', 'packages/api-client-typescript/src/generated');
  const trackedDart = git('ls-files', 'apps/mobile/lib/core/api/generated');
  assert.ok(trackedTs.trim().length > 0, 'the generated TypeScript client is not tracked');
  assert.ok(trackedDart.trim().length > 0, 'the generated Dart client is not tracked');

  // The gate regenerates l10n before analysing, so a fresh clone does not fail
  // on a missing generated file.
  assert.match(read('scripts/verify-clean-clone.sh'), /flutter pub get/);
});

test('test_EARS_E00_12_documented_commands_exist_as_make_targets', () => {
  // Every command the local-development guide tells a newcomer to run must
  // actually exist. Documentation that names a missing target is worse than no
  // documentation.
  const makefile = read('Makefile');
  const guide = read('docs/operations/local-development.md');

  const documented = [...guide.matchAll(/`make ([a-z-]+)`/g)].map((match) => match[1]!);
  assert.ok(documented.length > 5, 'the guide documents suspiciously few commands');

  for (const target of new Set(documented)) {
    assert.match(
      makefile,
      new RegExp(`^${target}:`, 'm'),
      `local-development.md documents \`make ${target}\`, which does not exist`,
    );
  }

  // The harness targets from before E00 must still work.
  for (const harnessTarget of ['next', 'status', 'validate', 'dashboard', 'hooks']) {
    assert.match(
      makefile,
      new RegExp(`^${harnessTarget}:`, 'm'),
      `harness target ${harnessTarget} was lost`,
    );
  }
});

test('test_EARS_E00_12_ci_runs_the_same_gate_a_developer_runs', () => {
  // If CI and local verification diverge, one of them is lying. The value of
  // `make verify` is that it is the same thing.
  const ci = read('.github/workflows/ci.yml');
  assert.ok(
    ci.includes('verify-clean-clone.sh') || ci.includes('make verify'),
    'CI does not run the clean-clone gate',
  );
});

test('test_EARS_E00_14_adr_audit_has_no_unmapped_consequence', () => {
  const audit = read('docs/architecture/adr-consequence-audit.md');

  // Every accepted ADR must appear. A missing one is a whole decision nobody
  // checked.
  for (let number = 1; number <= 9; number += 1) {
    const id = `ADR-000${number}`;
    assert.ok(audit.includes(id), `the audit does not cover ${id}`);
  }

  // No row may be left without a disposition.
  const rows = audit.split('\n').filter((line) => /^\| .+ \| .+ \| .+ \|$/.test(line));
  const statusRows = rows.filter((line) => !/^\| Consequence/.test(line) && !/^\|---/.test(line));
  assert.ok(statusRows.length > 30, 'the audit has suspiciously few consequence rows');

  for (const row of statusRows) {
    const cells = row.split('|').map((cell) => cell.trim());
    const status = cells[2] ?? '';
    assert.match(status, /✅|⏭️|🔒|N\/A/, `a consequence row has no disposition: ${row}`);
  }

  // A deferral must name where it went. "Later" is exactly the failure this
  // document exists to prevent (L-auth-002).
  for (const row of statusRows) {
    if (row.includes('⏭️')) {
      assert.match(row, /E0\d|epic|gate/i, `a deferred consequence names no owner: ${row}`);
    }
  }
});

test('test_EARS_E00_14_unresolved_decisions_are_recorded_not_guessed', () => {
  const openItems = read('infra/vm/recovery-open-items.md');
  const audit = read('docs/architecture/adr-consequence-audit.md');

  // The audit's locked rows and the open-items register must agree; two
  // divergent lists mean neither gets maintained.
  for (const decision of ['registry', 'secret manager', 'RPO', 'RTO', 'digest', 'supplier']) {
    assert.ok(
      openItems.toLowerCase().includes(decision.toLowerCase()),
      `open items omit the ${decision} decision`,
    );
  }

  assert.ok(
    audit.includes('🔒'),
    'the audit records no unresolved decision, which cannot be right',
  );

  // Process debt must be surfaced, not quietly ticked.
  assert.match(audit, /[Pp]eer review/);
  assert.match(audit, /QA/);
});

test('test_EARS_E00_14_rebuild_rehearsal_runs_and_refuses_production', () => {
  const output = execFileSync('bash', ['scripts/rehearse-vm-rebuild.sh', 'dry-run'], {
    cwd: repositoryRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  assert.match(output, /every source input is present/);
  // It must be explicit that a real rebuild is still blocked, rather than
  // implying the VM is recoverable today.
  assert.match(output, /UNRESOLVED HUMAN DECISIONS/);

  assert.throws(
    () =>
      execFileSync('bash', ['scripts/rehearse-vm-rebuild.sh', 'production'], {
        cwd: repositoryRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
      }),
    'the rehearsal accepted production as a target',
  );
});
